activeEnv: test_env
browser:
  browserName: chrome
  browserAttachScreenshot: false
  headlessMode: true
  browserTimeout: 60
  wait: 5
environments:
  test_env:
    envName: test_env
    appUrl: http://146.59.32.4/index.php
    title: TesterSii
    currencySymbolToReplace: $
    amountOfExpectedSearchResultsList: 1
    wantedProduct: HUMMINGBIRD
    minPrice: 9
    maxPrice: 13
    sliderStartingValue: 0
    sliderEndValue: 1
    menCategoryText: T-shirts, sweaters, hoodies and men's accessories.
    stationeryCategoryText: Notebooks, agendas, office accessories
    artCategoryText: Framed poster and vector images
    BasketPopupTestWantedProduct: THE BEST IS YET POSTER
    BasketPopupTestQuantity: 3
    RepetitionForBasketCalculations: 5
    shippingPrice: 7





